# Generated by Django 3.0.3 on 2020-04-03 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reproduccion', '0005_auto_20200328_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='genero',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
