# Generated by Django 3.0.3 on 2020-04-03 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reproduccion', '0007_generos'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='generos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Reproduccion.Generos'),
            preserve_default=False,
        ),
    ]
