# Generated by Django 3.0.3 on 2020-04-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reproduccion', '0008_album_generos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='duracion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='disquera',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generos',
            name='nombre',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
