# Generated by Django 3.0.3 on 2020-04-03 22:16

import Apps.Reproduccion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reproduccion', '0009_auto_20200403_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=Apps.Reproduccion.models.images_path),
        ),
    ]
