# Generated by Django 3.0.3 on 2020-05-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_auto_20200503_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pais',
            field=models.CharField(choices=[('MEX', 'Mexico'), ('USA', 'Estados Unidos')], default='Mexico', max_length=3),
        ),
    ]
