# Generated by Django 3.0.3 on 2020-05-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_auto_20200503_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pais',
            field=models.CharField(choices=[('MX', 'Mexico'), ('EU', 'Estados Unidos')], default='Mexico', max_length=10, null=True),
        ),
    ]
